services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  frontend:
    build: 
      context: ./frondend
    container_name: react_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: